**IT24100700 - Nawarathna H.M.P.P**

**Handling Missing Data**

In [2]:
#import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(color_codes=True)

In [3]:
#mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/crop_yeild_dataset.csv')
df.head()

,crop,region,N,P,K,temperature,humidity,rainfall,ph,area_ha,production_t
0,rice,Karnataka,70.7,43.6,54.9,27.2,61.2,255.9,6.95,268,928.2
1,rice,Punjab,108.8,46.9,43.4,25.5,58.7,87.0,7.08,605,2213.1
2,maize,West Bengal,91.9,34.7,30.4,27.5,73.5,349.9,5.99,410,2409.2
3,rice,Maharashtra,120.0,51.6,64.3,30.4,44.2,3.7,7.20,986,2303.9
4,sugarcane,Maharashtra,164.8,57.0,173.0,24.0,39.5,43.0,6.81,941,77299.3

In [6]:
#rename column headers
Crop_Table = df.rename(columns = {"crop":"Crop", "region": "Region", "N":"Nitrogen (N)","P":"Phosphorus (P)","K":"Potassium (K)","temperature": "Temperature (C)", "humidity": "Humidity", "rainfall":"Rainfall (mm)","ph":"Soil PH","area_ha":"Area (Hectare)", "production_t":"Production (Ton)"})
Crop_Table.head()

,Crop,Region,Nitrogen (N),Phosphorus (P),Potassium (K),Temperature (C),Humidity,Rainfall (mm),Soil PH,Area (Hectare),Production (Ton)
0,rice,Karnataka,70.7,43.6,54.9,27.2,61.2,255.9,6.95,268,928.2
1,rice,Punjab,108.8,46.9,43.4,25.5,58.7,87.0,7.08,605,2213.1
2,maize,West Bengal,91.9,34.7,30.4,27.5,73.5,349.9,5.99,410,2409.2
3,rice,Maharashtra,120.0,51.6,64.3,30.4,44.2,3.7,7.20,986,2303.9
4,sugarcane,Maharashtra,164.8,57.0,173.0,24.0,39.5,43.0,6.81,941,77299.3

In [7]:
#Check null values
if Crop_Table.isnull().sum().sum():
  print("\nNull values found.\n")
  print("0 Values Percentage = ", (((Crop_Table.isnull()).sum().sum() / len(Crop_Table)) * 100) ,"%")
else :
  print("\nNo Null values found.")
  print("Null Values Percentage = ", (((Crop_Table.isnull()).sum().sum() / len(Crop_Table)) * 100) ,"%")

#Check 0 values in Table
if (Crop_Table == 0).sum().sum():
  print("\n0 or 0.0 values found.")
  print("0 Values Percentage = ", (((Crop_Table == 0).sum().sum() / len(Crop_Table)) * 100) ,"%")
else:
  print("\nNo 0 or 0.0 values found.")
  print("0 Values Percentage = ", (((Crop_Table == 0).sum().sum() / len(Crop_Table)) * 100) ,"%")

No Null values found.
Null Values Percentage =  0.0 %

0 or 0.0 values found.
0 Values Percentage =  10.3648 %

In [9]:
# Delete rows where any column has a value of 0
New_Crop_Table = Crop_Table[~(Crop_Table == 0).any(axis=1)]
New_Crop_Table.head()

,Crop,Region,Nitrogen (N),Phosphorus (P),Potassium (K),Temperature (C),Humidity,Rainfall (mm),Soil PH,Area (Hectare),Production (Ton)
0,rice,Karnataka,70.7,43.6,54.9,27.2,61.2,255.9,6.95,268,928.2
1,rice,Punjab,108.8,46.9,43.4,25.5,58.7,87.0,7.08,605,2213.1
2,maize,West Bengal,91.9,34.7,30.4,27.5,73.5,349.9,5.99,410,2409.2
3,rice,Maharashtra,120.0,51.6,64.3,30.4,44.2,3.7,7.20,986,2303.9
4,sugarcane,Maharashtra,164.8,57.0,173.0,24.0,39.5,43.0,6.81,941,77299.3

In [10]:
#check 0 value in new table
if (New_Crop_Table == 0.0).sum().sum():
  print("\nMissing values found.")
  print("0 Values Percentage = ", (((New_Crop_Table == 0).sum().sum() / len(New_Crop_Table)) * 100) ,"%")
else:
  print("\nNo Missing values found.")
  print("0 Values Percentage = ", (((New_Crop_Table == 0).sum().sum() / len(New_Crop_Table)) * 100) ,"%")

No Missing values found.
0 Values Percentage =  0.0 %

**IT24100285 - Wijethunga W.M.O.H**

**Encode Categorical Variables**

In [11]:
#import library
pd.set_option("display.max_columns", None)

In [12]:
#Pandas One-Hot-Encoding
cat_cols = ['Crop', 'Region']
New_Crop_Table_ohe = pd.get_dummies(New_Crop_Table, columns=cat_cols, drop_first=False)
New_Crop_Table_ohe.head(), New_Crop_Table_ohe.shape

(   Nitrogen (N)  Phosphorus (P)  Potassium (K)  Temperature (C)  Humidity  \
 0          70.7            43.6           54.9             27.2      61.2
 1         108.8            46.9           43.4             25.5      58.7
 2          91.9            34.7           30.4             27.5      73.5
 3         120.0            51.6           64.3             30.4      44.2
 4         164.8            57.0          173.0             24.0      39.5

    Rainfall (mm)  Soil PH  Area (Hectare)  Production (Ton)  Crop_cotton  \
 0          255.9     6.95             268             928.2        False
 1           87.0     7.08             605            2213.1        False
 2          349.9     5.99             410            2409.2        False
 3            3.7     7.20             986            2303.9        False
 4           43.0     6.81             941           77299.3        False

    Crop_maize  Crop_rice  Crop_sugarcane  Crop_wheat  Region_Karnataka  \
 0       False       True           False       False              True
 1       False       True           False       False             False
 2        True      False           False       False             False
 3       False       True           False       False             False
 4       False      False            True       False             False

    Region_Maharashtra  Region_Punjab  Region_Tamil Nadu  Region_West Bengal
 0               False          False              False               False
 1               False           True              False               False
 2               False          False              False                True
 3                True          False              False               False
 4                True          False              False               False  ,
 (224088, 19))

**IT24102438 - Gamage L.G.W.P**

**Outlier Detection & Removal**

In [13]:
def make_numeric_New_Crop_Table_ohe(orig_New_Crop_Table_ohe):
    # convert strings with commas like "1,234" -> 1234
    numeric_New_Crop_Table_ohe = orig_New_Crop_Table_ohe.apply(lambda s: pd.to_numeric(s.astype(str).str.replace(',','').str.strip(), errors='coerce'))
    return numeric_New_Crop_Table_ohe

numeric_New_Crop_Table_ohe = make_numeric_New_Crop_Table_ohe(New_Crop_Table_ohe)
numeric_cols = [c for c in numeric_New_Crop_Table_ohe.columns if numeric_New_Crop_Table_ohe[c].notna().sum() > 0]
print("\nDetected numeric-ish columns (will be used for outlier checks):")
print(numeric_cols)

# show basic stats for numeric columns
if numeric_cols:
    display(numeric_New_Crop_Table_ohe[numeric_cols].describe().T)
else:
    print("No numeric columns detected. Check your CSV or column parsing.")

Detected numeric-ish columns (will be used for outlier checks):
['Nitrogen (N)', 'Phosphorus (P)', 'Potassium (K)', 'Temperature (C)', 'Humidity', 'Rainfall (mm)', 'Soil PH', 'Area (Hectare)', 'Production (Ton)']

,count,mean,std,min,25%,50%,75%,max
Nitrogen (N),224088.0,107.948278,30.366610,25.5,84.800,101.40,126.30,200.0
Phosphorus (P),224088.0,47.154953,15.918131,10.0,35.600,44.50,56.60,80.0
Potassium (K),224088.0,79.118190,63.166790,20.0,40.700,52.50,73.80,250.0
Temperature (C),224088.0,29.701816,4.043205,10.6,27.000,29.50,32.20,45.0
Humidity,224088.0,62.546534,13.740510,10.0,53.900,63.50,72.30,100.0
Rainfall (mm),224088.0,138.147339,94.031266,0.1,65.700,120.00,193.00,500.0
Soil PH,224088.0,6.703043,0.715690,4.0,6.170,6.75,7.27,9.0
Area (Hectare),224088.0,500.272353,288.352254,1.0,251.000,500.00,749.00,1000.0
Production (Ton),224088.0,9302.726962,18782.872100,1.0,803.775,1694.70,3540.55,110962.3

In [14]:
import math
from scipy import stats  # SciPy present in Colab; used for z-score

def iqr_bounds(series, k=1.5):
    # series should be numeric with NaNs allowed
    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    iqr = q3 - q1
    lower = q1 - k * iqr
    upper = q3 + k * iqr
    return lower, upper

def detect_outliers_iqr(series, k=1.5):
    lower, upper = iqr_bounds(series, k=k)
    return (series < lower) | (series > upper)

def detect_outliers_zscore(series, thresh=3.0):
    if series.dropna().shape[0] == 0:
        return pd.Series(False, index=series.index)
    std = series.std(ddof=0)
    if std == 0 or math.isnan(std):
        # constant series -> no z-score outliers
        return pd.Series(False, index=series.index)
    z = (series - series.mean()) / std
    return z.abs() > thresh

def outlier_summary(New_Crop_Table_ohe_numeric, method='iqr', k=1.5, z_thresh=3.0):
    # returns dict: {col: number_of_outliers}
    out_counts = {}
    for c in New_Crop_Table_ohe_numeric.columns:
        s = New_Crop_Table_ohe_numeric[c]
        if s.dropna().shape[0] == 0:
            out_counts[c] = 0
            continue
        if method == 'iqr':
            mask = detect_outliers_iqr(s, k=k)
        elif method == 'z':
            mask = detect_outliers_zscore(s, thresh=z_thresh)
        else:
            raise ValueError("method must be 'iqr' or 'z'")
        out_counts[c] = int(mask.sum())
    return out_counts

In [15]:
if not numeric_cols:
    print("No numeric columns to analyze.")
else:
    iqr_counts = outlier_summary(numeric_New_Crop_Table_ohe[numeric_cols], method='iqr', k=1.5)
    z_counts   = outlier_summary(numeric_New_Crop_Table_ohe[numeric_cols], method='z', z_thresh=3.0)

    summary_New_Crop_Table_ohe = pd.DataFrame({
        'iqr_outliers': pd.Series(iqr_counts),
        'z_outliers': pd.Series(z_counts),
        'non_nulls': numeric_New_Crop_Table_ohe[numeric_cols].notna().sum()
    })
    display(summary_New_Crop_Table_ohe.sort_values('iqr_outliers', ascending=False))

                  iqr_outliers  z_outliers  non_nulls
Potassium (K)            44828           0     224088
Production (Ton)         40689        7753     224088
Rainfall (mm)             3509        1500     224088
Temperature (C)           3349        1310     224088
Nitrogen (N)              2752        1104     224088
Humidity                  2513        1169     224088
Soil PH                    100         118     224088
Phosphorus (P)               0           0     224088
Area (Hectare)               0           0     224088

In [16]:
cols_to_check = numeric_cols
k = 1.5
how = 'any'

def remove_outliers_iqr(New_Crop_Table_ohe_orig, New_Crop_Table_ohe_numeric, cols=None, k=1.5, how='any'):
    if cols is None:
        cols = New_Crop_Table_ohe_numeric.columns.tolist()
    if how not in ('any','all'):
        raise ValueError("how must be 'any' or 'all'")
    masks = []
    for c in cols:
        s = New_Crop_Table_ohe_numeric[c]
        lower, upper = iqr_bounds(s, k=k)
        mask = (s < lower) | (s > upper)
        masks.append(mask.fillna(False))
    if not masks:
        return New_Crop_Table_ohe_orig.copy(), 0
    if how == 'any':
        combined = pd.concat(masks, axis=1).any(axis=1)
    else:
        combined = pd.concat(masks, axis=1).all(axis=1)
    removed_count = int(combined.sum())
    New_Crop_Table_ohe_cleaned = New_Crop_Table_ohe_orig.loc[~combined].copy()
    return New_Crop_Table_ohe_cleaned, removed_count

New_Crop_Table_ohe_iqr_clean, removed_iqr = remove_outliers_iqr(New_Crop_Table_ohe, numeric_New_Crop_Table_ohe, cols=cols_to_check, k=k, how=how)
print(f"IQR removal ('{how}', k={k}): removed {removed_iqr} rows. New shape: {New_Crop_Table_ohe_iqr_clean.shape} (old: {New_Crop_Table_ohe.shape})")

IQR removal ('any', k=1.5): removed 52498 rows. New shape: (171590, 19) (old: (224088, 19))

In [17]:
#Rename Table
NT = New_Crop_Table_ohe
print(NT.head())

   Nitrogen (N)  Phosphorus (P)  Potassium (K)  Temperature (C)  Humidity  \
0          70.7            43.6           54.9             27.2      61.2
1         108.8            46.9           43.4             25.5      58.7
2          91.9            34.7           30.4             27.5      73.5
3         120.0            51.6           64.3             30.4      44.2
4         164.8            57.0          173.0             24.0      39.5

   Rainfall (mm)  Soil PH  Area (Hectare)  Production (Ton)  Crop_cotton  \
0          255.9     6.95             268             928.2        False
1           87.0     7.08             605            2213.1        False
2          349.9     5.99             410            2409.2        False
3            3.7     7.20             986            2303.9        False
4           43.0     6.81             941           77299.3        False

   Crop_maize  Crop_rice  Crop_sugarcane  Crop_wheat  Region_Karnataka  \
0       False       True           False       False              True
1       False       True           False       False             False
2        True      False           False       False             False
3       False       True           False       False             False
4       False      False            True       False             False

   Region_Maharashtra  Region_Punjab  Region_Tamil Nadu  Region_West Bengal
0               False          False              False               False
1               False           True              False               False
2               False          False              False                True
3                True          False              False               False
4                True          False              False               False

**IT24101058 - Wijerathna B.G.G.S**

**Feature Engineering (Creation/Selection)**

In [18]:
#Total Fertilzer (TF)
NT['TF'] = NT['Nitrogen (N)'] + NT['Phosphorus (P)'] + NT['Potassium (K)']

#Fertilizer Efficiency Ratios (FER)
NT['FER'] = NT['Production (Ton)'] / (NT['TF'] + 0.001)

#Climate interaction features
NT['THI'] = NT['Temperature (C)'] * NT['Humidity'] #(THI)
NT['TRI'] = NT['Temperature (C)'] * NT['Rainfall (mm)'] #(TRI)

print(NT.head())

   Nitrogen (N)  Phosphorus (P)  Potassium (K)  Temperature (C)  Humidity  \
0          70.7            43.6           54.9             27.2      61.2
1         108.8            46.9           43.4             25.5      58.7
2          91.9            34.7           30.4             27.5      73.5
3         120.0            51.6           64.3             30.4      44.2
4         164.8            57.0          173.0             24.0      39.5

   Rainfall (mm)  Soil PH  Area (Hectare)  Production (Ton)  Crop_cotton  \
0          255.9     6.95             268             928.2        False
1           87.0     7.08             605            2213.1        False
2          349.9     5.99             410            2409.2        False
3            3.7     7.20             986            2303.9        False
4           43.0     6.81             941           77299.3        False

   Crop_maize  Crop_rice  Crop_sugarcane  Crop_wheat  Region_Karnataka  \
0       False       True           False       False              True
1       False       True           False       False             False
2        True      False           False       False             False
3       False       True           False       False             False
4       False      False            True       False             False

   Region_Maharashtra  Region_Punjab  Region_Tamil Nadu  Region_West Bengal  \
0               False          False              False               False
1               False           True              False               False
2               False          False              False                True
3                True          False              False               False
4                True          False              False               False

      TF         FER      THI      TRI
0  169.2    5.485783  1664.64  6960.48
1  199.1   11.115464  1496.85  2218.50
2  157.0   15.345125  2021.25  9622.25
3  235.9    9.766385  1343.68   112.48
4  394.8  195.793070   948.00  1032.00

**IT24101553 - Wickramarachchi D.S**

**Normalization, Scaling & Standardization**

In [19]:
# Normalization using MinMaxScaler (scales features to [0, 1] range)
from sklearn.preprocessing import MinMaxScaler, StandardScaler

target = 'Production (Ton)'
numeric_cols = NT.select_dtypes(include=[np.number]).columns.drop([target])

scaler_minmax = MinMaxScaler()
NT_minmax = NT.copy()
NT_minmax[numeric_cols] = scaler_minmax.fit_transform(NT_minmax[numeric_cols])

print("\nAfter MinMax Scaling:")
print(NT_minmax[numeric_cols].describe())

After MinMax Scaling:
        Nitrogen (N)  Phosphorus (P)  Potassium (K)  Temperature (C)  \
count  224088.000000   224088.000000  224088.000000    224088.000000
mean        0.472483        0.530785       0.257036         0.555285
std         0.174021        0.227402       0.274638         0.117535
min         0.000000        0.000000       0.000000         0.000000
25%         0.339828        0.365714       0.090000         0.476744
50%         0.434957        0.492857       0.141304         0.549419
75%         0.577650        0.665714       0.233913         0.627907
max         1.000000        1.000000       1.000000         1.000000

            Humidity  Rainfall (mm)        Soil PH  Area (Hectare)  \
count  224088.000000  224088.000000  224088.000000   224088.000000
mean        0.583850       0.276150       0.540609        0.499772
std         0.152672       0.188100       0.143138        0.288641
min         0.000000       0.000000       0.000000        0.000000
25%         0.487778       0.131226       0.434000        0.250250
50%         0.594444       0.239848       0.550000        0.499499
75%         0.692222       0.385877       0.654000        0.748749
max         1.000000       1.000000       1.000000        1.000000

                  TF            FER            THI            TRI
count  224088.000000  224088.000000  224088.000000  224088.000000
mean        0.337859       0.078860       0.392979       0.223769
std         0.216004       0.134345       0.104556       0.149469
min         0.000000       0.000000       0.000000       0.000000
25%         0.197224       0.012929       0.324625       0.108226
50%         0.257667       0.026491       0.394395       0.197142
75%         0.344079       0.055017       0.462497       0.312569
max         1.000000       1.000000       1.000000       1.000000

In [20]:
NT_scaled = NT.copy()  # a copy of the data frame

# Manually specifing columns
scale_cols = ["Nitrogen (N)", "Phosphorus (P)", "Potassium (K)", "Temperature (C)", "Humidity", "Rainfall (mm)", "Soil PH", "Area (Hectare)", "TF", "FER", "THI", "TRI"]

# Apply scaling
scaler = MinMaxScaler()
NT_scaled[scale_cols] = scaler.fit_transform(NT_scaled[scale_cols])

print("\nScaled DataFrame:")
display(NT_scaled.head())

Scaled DataFrame:

,Nitrogen (N),Phosphorus (P),Potassium (K),Temperature (C),Humidity,Rainfall (mm),Soil PH,Area (Hectare),Production (Ton),Crop_cotton,Crop_maize,Crop_rice,Crop_sugarcane,Crop_wheat,Region_Karnataka,Region_Maharashtra,Region_Punjab,Region_Tamil Nadu,Region_West Bengal,TF,FER,THI,TRI
0,0.259026,0.480000,0.151739,0.482558,0.568889,0.511702,0.590,0.267267,928.2,False,False,True,False,False,True,False,False,False,False,0.192299,0.016426,0.349786,0.386629
1,0.477364,0.527143,0.101739,0.433140,0.541111,0.173835,0.616,0.604605,2213.1,False,False,True,False,False,False,False,True,False,False,0.259234,0.033302,0.310334,0.123158
2,0.380516,0.352857,0.045217,0.491279,0.705556,0.699740,0.398,0.409409,2409.2,False,True,False,False,False,False,False,False,False,True,0.164988,0.045981,0.433635,0.534521
3,0.541547,0.594286,0.192609,0.575581,0.380000,0.007201,0.640,0.985986,2303.9,False,False,True,False,False,False,True,False,False,False,0.341616,0.029258,0.274319,0.006145
4,0.798281,0.671429,0.665217,0.389535,0.327778,0.085817,0.562,0.940941,77299.3,False,False,False,True,False,False,True,False,False,False,0.697336,0.586906,0.181284,0.057234

In [21]:
#StandardScaler implementation
# Manually specifying columns
scale_cols = ["Nitrogen (N)", "Phosphorus (P)", "Potassium (K)", "Temperature (C)", "Humidity", "Rainfall (mm)", "Soil PH", "Area (Hectare)", "TF", "FER", "THI", "TRI"]

# Create scaler object
scaler = StandardScaler()

# Apply standardization
NT_standard = NT_scaled.copy()
NT_standard[scale_cols] = scaler.fit_transform(NT_standard[scale_cols])

# Display results
print("After Standard Scaling (mean=0, std=1):")
NT_standard[scale_cols].head()

After Standard Scaling (mean=0, std=1):

,Nitrogen (N),Phosphorus (P),Potassium (K),Temperature (C),Humidity,Rainfall (mm),Soil PH,Area (Hectare),TF,FER,THI,TRI
0,-1.226622,-0.223328,-0.383402,-0.618772,-0.097998,1.252274,0.345062,-0.805518,-0.673876,-0.464734,-0.413108,1.089592
1,0.028048,-0.016017,-0.565460,-1.039231,-0.279942,-0.543941,0.526706,0.363194,-0.363995,-0.339117,-0.790439,-0.673129
2,-0.528486,-0.782440,-0.771264,-0.544573,0.797168,2.251944,-0.996304,-0.313063,-0.800315,-0.244740,0.388846,2.079043
3,0.396875,0.279245,-0.234589,0.172681,-1.335218,-1.429818,0.694376,1.684498,0.017397,-0.369220,-1.134891,-1.455993
4,1.872183,0.618481,1.486256,-1.410225,-1.677273,-1.011871,0.149446,1.528438,1.664220,3.781643,-2.024707,-1.114183

**IT24103125 - Bandara W.M.P.G.L.D**

**Feature Engineering (Dimension Reduction)**

In [ ]:
#print standarized new table
print(NT_standard.head())

   Nitrogen (N)  Phosphorus (P)  Potassium (K)  Temperature (C)  Humidity   \
0     -1.226622       -0.223328      -0.383402        -0.618772  -0.097998
1      0.028048       -0.016017      -0.565460        -1.039231  -0.279942
2     -0.528486       -0.782440      -0.771264        -0.544573   0.797168
3      0.396875        0.279245      -0.234589         0.172681  -1.335218
4      1.872183        0.618481       1.486256        -1.410225  -1.677273

   Rainfall (mm)   Soil PH  Area (Hectare)  Production (Ton)  Crop_cotton  \
0       1.252274  0.345062       -0.805518             928.2        False
1      -0.543941  0.526706        0.363194            2213.1        False
2       2.251944 -0.996304       -0.313063            2409.2        False
3      -1.429818  0.694376        1.684498            2303.9        False
4      -1.011871  0.149446        1.528438           77299.3        False

   Crop_maize  Crop_rice  Crop_sugarcane  Crop_wheat  Region_Karnataka  \
0       False       True           False       False              True
1       False       True           False       False             False
2        True      False           False       False             False
3       False       True           False       False             False
4       False      False            True       False             False

   Region_Maharashtra  Region_Punjab  Region_Tamil Nadu  Region_West Bengal  \
0               False          False              False               False
1               False           True              False               False
2               False          False              False                True
3                True          False              False               False
4                True          False              False               False

         TF       FER       THI       TRI
0 -0.673876 -0.464734 -0.413108  1.089592
1 -0.363995 -0.339117 -0.790439 -0.673129
2 -0.800315 -0.244740  0.388846  2.079043
3  0.017397 -0.369220 -1.134891 -1.455993
4  1.664220  3.781643 -2.024707 -1.114183

In [22]:
#import libraries
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [23]:
target = "Production (Ton)"
numeric_cols = NT_standard.select_dtypes(include="number").columns.drop(target)

#Scale numeric features
scaler = StandardScaler()
scaled_data = scaler.fit_transform(NT_standard[numeric_cols])

#Run PCA
pca = PCA(n_components=2, random_state=42)
pca_result = pca.fit_transform(scaled_data)

#Save PCA results in new dataframe
F_Dataset = NT_standard.copy()
F_Dataset["PCA1"] = pca_result[:, 0]
F_Dataset["PCA2"] = pca_result[:, 1]

print("Final Shape:", F_Dataset.shape)
print(F_Dataset[["PCA1", "PCA2"]].head())

Final Shape: (224088, 25)
       PCA1      PCA2
0 -1.375043  0.895070
1 -0.569684 -1.163250
2 -1.428215  3.102464
3  0.112201 -2.761177
4  4.273469 -2.541379

In [ ]:
#display final dataset
print(F_Dataset.head())

   Nitrogen (N)  Phosphorus (P)  Potassium (K)  Temperature (C)  Humidity   \
0     -1.226622       -0.223328      -0.383402        -0.618772  -0.097998
1      0.028048       -0.016017      -0.565460        -1.039231  -0.279942
2     -0.528486       -0.782440      -0.771264        -0.544573   0.797168
3      0.396875        0.279245      -0.234589         0.172681  -1.335218
4      1.872183        0.618481       1.486256        -1.410225  -1.677273

   Rainfall (mm)   Soil PH  Area (Hectare)  Production (Ton)  Crop_cotton  \
0       1.252274  0.345062       -0.805518             928.2        False
1      -0.543941  0.526706        0.363194            2213.1        False
2       2.251944 -0.996304       -0.313063            2409.2        False
3      -1.429818  0.694376        1.684498            2303.9        False
4      -1.011871  0.149446        1.528438           77299.3        False

   Crop_maize  Crop_rice  Crop_sugarcane  Crop_wheat  Region_Karnataka  \
0       False       True           False       False              True
1       False       True           False       False             False
2        True      False           False       False             False
3       False       True           False       False             False
4       False      False            True       False             False

   Region_Maharashtra  Region_Punjab  Region_Tamil Nadu  Region_West Bengal  \
0               False          False              False               False
1               False           True              False               False
2               False          False              False                True
3                True          False              False               False
4                True          False              False               False

         TF       FER       THI       TRI      PCA1      PCA2
0 -0.673876 -0.464734 -0.413108  1.089592 -1.375043  0.895070
1 -0.363995 -0.339117 -0.790439 -0.673129 -0.569684 -1.163250
2 -0.800315 -0.244740  0.388846  2.079043 -1.428215  3.102464
3  0.017397 -0.369220 -1.134891 -1.455993  0.112201 -2.761177
4  1.664220  3.781643 -2.024707 -1.114183  4.273469 -2.541379

In [24]:
#Download final processed dataset
F_Dataset.to_csv('Final_Dataset.csv', index=False)
from google.colab import files
files.download('Final_Dataset.csv')